export const eventNameConfig = {
    'view_promotion': 'view_promotion',
    'select_item': 'select_item',
    'select_promotion': 'select_promotion',
    'view_item': 'view_item',
    'view_item_list': 'view_item_list',
    'LS_MB_productImpression': 'LS_MB_productImpression',
    'ls_viewItemImpression': 'ls_viewItemImpression',
    'viewItemListImpression': 'viewItemListImpression',
    'LS_MB_promotionImpression': 'LS_MB_promotionImpression',
    'login': 'login',
    'sign_up': 'sign_up',
    'logout': 'logout',
    'USER_LOGOUT': 'USER_LOGOUT',
    'reactSignUpEvent': 'reactSignUpEvent',
    'reactLoginEvent': 'reactLoginEvent',
    'UNSUCCESSFULL_LOGIN': 'UNSUCCESSFULL_LOGIN',
    'LS_MB_productClick': 'LS_MB_productClick',
    'LS_MB_productDetail': 'LS_MB_productDetail',
    'purchase': 'purchase',
    'begin_checkout': 'begin_checkout',
    'add_shipping_info': 'add_shipping_info',
    'add_payment_info': 'add_payment_info',
    'order_initiated': 'order_initiated',
    'view_cart': 'view_cart',
    'add_to_wishlist': 'add_to_wishlist',
    'cart_update': 'cart_update',
    'add_to_cart': 'add_to_cart',
    'buy_now': 'buy_now',
    'action_addToCart': 'add_to_cart',
    'action_addBuyNow': 'buy_now',
    'action_wishList': 'add_to_wishlist',
    'CLICK_CART_VIEW':'CART_VIEW',
    'remove_from_cart':'remove_from_cart',
};